### ISSUE TITLE
question(): gnome 3.36 support

### ISSUE THREAD

**Issue by ubone** [kiyui/gnome-shell-night-light-slider-extension#57]
pls

**Comment by trthomps** [comment]
Error from logs ```Mar 09 13:02:22 travis-x1-carbon gnome-software[1896]: night-light-slider.timur_linux.com has error: Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
```

**Comment by kiyui** [comment]
Hi, I'll get to reviewing #58 after work and see if I can get it fixed. What distro are yous using that has 3.36 already?

**Comment by Rodancoci** [comment]
I'm using Arch and it has already rolled out 3.36

**Comment by kiyui** [comment]
Hey, I've published the extension and am awaiting review. For now, you can use the version [here](https://github.com/kiyui/gnome-shell-night-light-slider-extension/releases/tag/14.0).

I'll close this issue once it's been released

**Comment by ubone** [comment]
thank you <3

(can't use the extension website anyway)

**Comment by Rodancoci** [comment]
Extension website version is working perfectly! Thank you!

**Comment by kiyui** [comment]
Version 14 is active now:
https://extensions.gnome.org/review/14444

Enjoy :smile:
