### ISSUE TITLE
request(): mouse wheel

### ISSUE THREAD

**Issue by ubone** [kiyui/gnome-shell-night-light-slider-extension#62]
if you put the cursor over the volume icon in the top bar you can use the mouse wheel to change the volume

would be nice to have if it's not too much work

**Comment by kiyui** [comment]
Hi, this should be fixed and working in the [latest version](https://github.com/kiyui/gnome-shell-night-light-slider-extension/releases/tag/17.0) and in fact should have always been working :sweat_smile:
